services:
  backend:
    image: code-backend:latest
    container_name: fastapi_backend
    restart: always
    env_file:
      - ./backend/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - chroma
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql://admin:admin@postgres:5432/veille_db
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma
    container_name: chroma_db
    restart: always
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  postgres_data:
  chroma_data: