"""add search_status

Revision ID: 17b62adc37af
Revises: 20a6dc447fa4
Create Date: 2026-07-27 12:07:56.549784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b62adc37af'
down_revision: Union[str, Sequence[str], None] = '20a6dc447fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'search_status')
    # ### end Alembic commands ###
