"""add email_sent to users

Revision ID: 20a6dc447fa4
Revises: ef0bdc90d1c8
Create Date: 2026-07-27 09:34:22.311176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a6dc447fa4'
down_revision: Union[str, Sequence[str], None] = 'ef0bdc90d1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_sent')
    # ### end Alembic commands ###
